################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= vector_reduction 
# Cuda source files (compiled with cudacc)
CUFILES		:= vector_reduction.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= vector_reduction_gold.cpp 

# Include Debug Information? (0 = No, 1 = Yes)
#dbg = 1

################################################################################
# Rules and targets

include ../../common/common.mk
