################################################################################
#
# Build script for project
#
################################################################################

# Ad source files here
EXECUTABLE	:= vec_mat_mult
# Cuda source files (compiled with cudacc)
CUFILES		:= vec_mat_mult.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \
	vec_mat_mult_gold.cpp

################################################################################
# Rules and targets

include ../../common/common.mk
