################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= compact_stream
# Cuda source files (compiled with cudacc)
CUFILES		:= compact_stream.cu 
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \
	compact_stream_gold.cpp \


################################################################################
# Rules and targets

include ../../common/common.mk
